version: '3.8'

services:
  testing_service:
    image: langchain_mem0
    container_name: langchain_mem0
    ports:
      - "8009:8000"
    #command: streamlit run app.py
    command: tail -f /dev/null
    environment:
      - OPENAI_API_KEY=sk-proj-yourapi
      - ANTHROPIC_API_KEY=sk-ant-api03-yourapi

#docker exec -it langchain_mem0 /bin/bash
#podman exec -it langchain_mem0 /bin/bash