#version: '3'

services:
  realestate-datachat:
    image: st_datachat_langchainmd
    container_name: st_datachat_langchainmd
    volumes:
      - ai_st_datachat_langchainmd:/app
    working_dir: /app
    #command: /bin/sh -c "\
    #  streamlit run RealEstate.py"
    command: tail -f /dev/null 
    ports:
      - "8501:8501"
    restart: always
    environment:
      MODEL_API_KEY: sk-proj-openaiAPIhere
    # networks:
    #   - cloudflare_tunnel
      # - nginx_default   
    #restart: always   

# networks:
#   cloudflare_tunnel:
#     external: true
  # nginx_default:
  #   external: true

volumes:
  ai_st_datachat_langchainmd:

#docker exec -it st_datachat_langchainmd /bin/bash 