version: '3.8'

services:
  testing_service:
    image: properties_chat
    container_name: Chat_with_Properties
    ports:
      - "8009:8000"
    command: tail -f /dev/null ##command: streamlit run app.py
    environment:
      - OPENAI_API_KEY=sk-proj-yourapi #without quotes here
      - ANTHROPIC_API_KEY=sk-ant-api03-yourapi #without quotes here

#docker exec -it Chat_with_Properties /bin/bash
#podman exec -it Chat_with_Properties /bin/bash