name: CI/CD Build MultiArch

on:
  # push:
  #   branches:
  #     - main
  repository_dispatch:
    types: [run-workflow]  # Customize this with your own event name      

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CICD_TOKEN_DataChat }}

    - name: Build and push Docker image of LLamaIndex with Mem0
      uses: docker/build-push-action@v2
      with:
        context: ./LLamaIndex/With_Mem0
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/jalcocert/data-chat:properties

    - name: Build and push Docker image of LangChain
      uses: docker/build-push-action@v2
      with:
        context: ./LangChain
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/jalcocert/data-chat:langchain